language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  include:
    - php: 8.0.2
    - php: 8.1
    - php: 8.2

install: travis_retry composer update

script:
  - php vendor/bin/phpunit --coverage-text

notifications:
    email: false
